tarantool:
        image: tarantool/tarantool:1.7.4
        container_name: chronograph_tarantool
        command: tarantool /opt/tarantool/app.lua
        volumes:
            - ./state/tarantool/conf:/opt/tarantool
            - ./state/tarantool/_data:/var/lib/tarantool
        environment:
            TARANTOOL_USER_NAME: chrono
            TARANTOOL_USER_PASSWORD: chrono
        ports:
            - "3301:3301"
        labels:
            - "traefik=false"
